# Generated by Django 3.0.5 on 2020-04-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeveloperJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('senders_name', models.CharField(max_length=50)),
                ('senders_email', models.EmailField(max_length=50)),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField()),
                ('ui_design', models.BooleanField(default=True)),
                ('design_documentation', models.BooleanField(default=False)),
                ('favicon', models.BooleanField(default=False)),
                ('branding', models.BooleanField(default=False)),
                ('custom_domain', models.BooleanField(default=True)),
                ('web_hosting', models.BooleanField(default=False)),
                ('storage_database', models.BooleanField(default=True)),
                ('transactional_emails', models.BooleanField(default=False)),
                ('admin_panel', models.BooleanField(default=False)),
                ('responsiveness', models.BooleanField(default=False)),
                ('payment_config', models.BooleanField(default=False)),
                ('seo', models.BooleanField(default=False)),
                ('google_analytics', models.BooleanField(default=False)),
                ('blog', models.BooleanField(default=False)),
                ('social_acc_integration', models.BooleanField(default=False)),
                ('perfective_features', models.BooleanField(default=False)),
                ('domain_security', models.BooleanField(default=False)),
                ('app_security', models.BooleanField(default=False)),
                ('privacy_policy', models.BooleanField(default=False)),
                ('terms_and_conditions', models.BooleanField(default=False)),
                ('additional_features', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
