# Generated by Django 3.0.5 on 2020-04-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200423_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirewebdev',
            name='branding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hirewebdev',
            name='favicon',
            field=models.BooleanField(default=False),
        ),
    ]
