# Generated by Django 3.0.5 on 2020-04-27 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200423_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HireWebDev',
        ),
    ]
